# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import video_encoding.fields
import video_encoding.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(editable=False)),
                ('field_name', models.CharField(max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Progress')),
                ('format', models.CharField(editable=False, max_length=255, verbose_name='Format')),
                ('file', video_encoding.fields.VideoField(editable=False, height_field='height', max_length=2048, upload_to=video_encoding.models.upload_format_to, verbose_name='File', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True, verbose_name='Width')),
                ('height', models.PositiveIntegerField(editable=False, null=True, verbose_name='Height')),
                ('duration', models.PositiveIntegerField(editable=False, null=True, verbose_name='Duration (s)')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
            },
        ),
    ]
