# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_encoding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='object_id',
            field=models.TextField(db_index=True, editable=False),
        ),
    ]
